### ISSUE TITLE
NoSuchElementException when presses Tab

### ISSUE THREAD

**Issue by kuro46** [kuro46/CommandUtility#8]
When presses Tab at
```
/command subcommand |
                    ↑here
```
Exception:
```
Caused by: java.util.NoSuchElementException: List is empty.
        at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:362) ~[?:?]
        at com.github.kuro46.commandutility.syntax.CommandSyntax.parseCompleting(CommandSyntax.kt:67) ~[?:?]
        at com.github.kuro46.commandutility.handle.CommandManager.getCandidatesByHandler(CommandManager.kt:194) ~[?:?]
        at com.github.kuro46.commandutility.handle.CommandManager.executeTabComplete(CommandManager.kt:166) ~[?:?]
        at com.github.kuro46.commandutility.handle.CommandManager.access$executeTabComplete(CommandManager.kt:13) ~[?:?]
        at com.github.kuro46.commandutility.handle.CommandManager$TabExecutorImpl.onTabComplete(CommandManager.kt:230) ~[?:?]
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:132) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 14 more
```

**Comment by kuro46** [comment]
Fixed in 147ca28.
